name: Export Changelog from Figma
on: [push]
jobs:
  all:
    name: Figma Export
    runs-on: ubuntu-latest
    steps:
      - uses: primer/figma-action@v1.0.0-alpha.3
        with:
          args: "format=svg outputDir=./build/"
        env:
          FIGMA_FILE_URL: "https://www.figma.com/file/2ruSnPauajQGprFy6K333u/Desktop-Components?node-id=0%3A1"
          FIGMA_TOKEN: 320808-eb7cccd5-325c-4bce-b985-80971609d244
